<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_userLogged</name>
   <tag></tag>
   <elementGuidId>c8cda4a2-8f7e-4366-8d05-e6289aed2c19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li/child::a/child::b</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
